In [45]:
import pandas as pd
import xgboost as xgb
import numpy as np
from sklearn import datasets, linear_model

In [50]:
X_train = pd.read_csv('X_train_prep')

In [51]:
X_test = pd.read_csv('X_test_prep')

In [70]:
X= pd.read_csv('/Users/mi0310/Desktop/JPMC/train.csv')
Y_train = X["Fare"]

In [71]:
regr = linear_model.LinearRegression()

In [72]:
regr.fit(X_train, Y_train)

# Make predictions using the testing set
y_pred = regr.predict(X_test)

In [73]:
y_pred

array([ -981.2256282 ,  1381.3860646 , 12947.34240612, ...,
        5608.24260903, 12764.41133458, 11679.88294385])

In [75]:
np.savetxt("y_pred_updated.csv", y_pred, delimiter=",")

In [6]:
xgdmat=xgb.DMatrix(X_train,Y_train)
our_params={'eta':0.1,'seed':0,'subsample':0.8,'colsample_bytree':0.8,'objective':'reg:linear','max_depth':3,'min_child_weight':1}
final_gb=xgb.train(our_params,xgdmat)
tesdmat=xgb.DMatrix(X_test)
y_pred=final_gb.predict(tesdmat)
print(y_pred)

[2986.5415 3468.0735 7804.505  ... 5286.446  7804.505  8531.245 ]


In [8]:
y_pred

array([2986.5415, 3468.0735, 7804.505 , ..., 5286.446 , 7804.505 ,
       8531.245 ], dtype=float32)

In [9]:
y = pd.DataFrame(y_pred)

In [13]:
y.to_csv('Y_test.csv')

In [14]:
y_pred

array([2986.5415, 3468.0735, 7804.505 , ..., 5286.446 , 7804.505 ,
       8531.245 ], dtype=float32)

In [18]:
np.savetxt("y_pred.csv", y_pred, delimiter=",")

In [19]:
y_pred

array([2986.5415, 3468.0735, 7804.505 , ..., 5286.446 , 7804.505 ,
       8531.245 ], dtype=float32)

In [23]:
X_train.dtypes

From                    int64
To                      int64
Flight Time             int64
Class                   int64
Age_at_Booking          int64
Booking_to_flight       int64
Booking Year            int64
Booking Month           int64
Booking Is_month_end     bool
Flight Year             int64
Flight Month            int64
Flight Dayofweek        int64
Flight Is_month_end      bool
Time Label              int64
dtype: object

In [13]:
del X_train["Unnamed: 0"]

In [15]:
del X_train["Booking Dayofweek"]

In [16]:
del X_train["Booking Is_month_start"]

In [17]:
del X_train["Flight Is_month_start"]

In [21]:
X_test = X_test.drop(["Unnamed: 0","Booking Dayofweek","Booking Is_month_start","Flight Is_month_start"],axis = 1)

In [22]:
X_test.dtypes

From                    int64
To                      int64
Flight Time             int64
Class                   int64
Age_at_Booking          int64
Booking_to_flight       int64
Booking Year            int64
Booking Month           int64
Booking Is_month_end     bool
Flight Year             int64
Flight Month            int64
Flight Dayofweek        int64
Flight Is_month_end      bool
Time Label              int64
dtype: object

In [30]:
del X_train["Flight Year"]
del X_test["Flight Year"]

In [49]:
X_test

Unnamed: 0  Unnamed: 0.1  From  To  Flight Time  Class  Age_at_Booking  \
0              0             0     1   3           19      0              11   
1              1             1     3   1           17      0              54   
2              2             2     3   1           13      1              49   
3              3             3     3   2           13      0              58   
4              4             4     7   1           17      0              16   
5              5             5     7   6            9      0              30   
6              6             6     3   1           20      1              42   
7              7             7     4   1           17      0              65   
8              8             8     2   6           11      0              25   
9              9             9     4   1            6      0              71   
10            10            10     7   3           11      0              37   
11            11            11     3   2            0      0              58   
12            12            12     1   3           22      0              61   
13            13            13     4   2            5      0              75   
14            14            14     6   3           13      0              52   
15            15            15     1   3           22      0              64   
16            16            16     3   4           18      0              49   
17            17            17     7   3           12      0              42   
18            18            18     5   2           10      0              44   
19            19            19     5   4           14      1              27   
20            20            20     1   6           20      0              13   
21            21            21     2   6            3      0              62   
22            22            22     7   3           17      0              21   
23            23            23     4   1            7      0              30   
24            24            24     7   1           16      0              43   
25            25            25     5   7            6      0              19   
26            26            26     2   4           12      0              53   
27            27            27     3   5           16      0              27   
28            28            28     2   7            8      1              42   
29            29            29     3   7           18      0              54   
...          ...           ...   ...  ..          ...    ...             ...   
2470        2470          2470     3   2            2      0              45   
2471        2471          2471     3   4           23      0              34   
2472        2472          2472     3   4           19      0              55   
2473        2473          2473     2   5           16      0              41   
2474        2474          2474     7   2           11      0              16   
2475        2475          2475     2   7           14      0              36   
2476        2476          2476     1   3           19      0              26   
2477        2477          2477     3   2           20      1              64   
2478        2478          2478     2   3           15      0              44   
2479        2479          2479     4   2            5      0              37   
2480        2480          2480     3   2           15      0              45   
2481        2481          2481     5   1            6      0              67   
2482        2482          2482     6   7           11      0              47   
2483        2483          2483     4   3           10      1              67   
2484        2484          2484     1   3           22      0              16   
2485        2485          2485     4   3           20      0              64   
2486        2486          2486     5   6            8      1              51   
2487        2487          2487     3   2           18      0              45   
2488  

In [53]:
del X_train["Unnamed: 0"]
del X_test["Unnamed: 0"]

In [58]:
del X_test["Unnamed: 0.1"]

In [62]:
X_test.dtypes

From                      int64
To                        int64
Flight Time               int64
Class                     int64
Age_at_Booking            int64
Booking_to_flight         int64
Booking Year              int64
Booking Month             int64
Booking Dayofweek         int64
Booking Is_month_end       bool
Booking Is_month_start     bool
Flight Year               int64
Flight Month              int64
Flight Dayofweek          int64
Flight Is_month_end        bool
Flight Is_month_start      bool
Time Label                int64
dtype: object

In [63]:
del X_train["Flight Time"]
del X_test["Flight Time"]
del X_train["Booking Dayofweek"]
del X_test["Booking Dayofweek"]

In [68]:
X_test.dtypes


From                      int64
To                        int64
Class                     int64
Age_at_Booking            int64
Booking_to_flight         int64
Booking Month             int64
Booking Is_month_end       bool
Booking Is_month_start     bool
Flight Month              int64
Flight Dayofweek          int64
Flight Is_month_end        bool
Flight Is_month_start      bool
Time Label                int64
dtype: object

In [69]:
X_train.dtypes

From                      int64
To                        int64
Class                     int64
Age_at_Booking            int64
Booking_to_flight         int64
Booking Month             int64
Booking Is_month_end       bool
Booking Is_month_start     bool
Flight Month              int64
Flight Dayofweek          int64
Flight Is_month_end        bool
Flight Is_month_start      bool
Time Label                int64
dtype: object

In [67]:
del X_train["Flight Year"]
del X_test["Flight Year"]
del X_train["Booking Year"]
del X_test["Booking Year"]

In [76]:
xgdmat=xgb.DMatrix(X_train,Y_train)
our_params={'eta':0.1,'seed':0,'subsample':0.8,'colsample_bytree':0.8,'objective':'reg:linear','max_depth':3,'min_child_weight':1}
final_gb=xgb.train(our_params,xgdmat)
tesdmat=xgb.DMatrix(X_test)
y_pred=final_gb.predict(tesdmat)
print(y_pred)

[2909.0535 3609.8606 8095.077  ... 5192.6094 7596.0176 8302.021 ]


In [77]:
np.savetxt("y_pred_xgboost.csv", y_pred, delimiter=",")